chartVersion: 0.2.5

project:
  name: "portfolio"

repository:
  name: "markmorcos/portfolio"
  path: "."

ingress:
  host: morcos.tech
  rules:
    - host: morcos.tech
      path: /
      pathType: Prefix
      serviceName: portfolio-service

deployments:
  - name: portfolio-deployment
    image: markmorcos/portfolio

services:
  - name: portfolio-service
    port: 80
