version: 0.8.2

namespace: portfolio
project: portfolio

services:
  - name: portfolio
    image: ghcr.io/markmorcos/portfolio
    port: 80

    ingress:
      host: markmorcos.dev
      path: /
      pathType: Prefix
