version: 0.5.0

namespace: portfolio
project: portfolio

services:
  - name: portfolio
    image: ghcr.io/markmorcos/portfolio
    port: 80

    ingress:
      host: morcos.tech
      path: /
      pathType: Prefix
