version: 0.4.7

namespace: portfolio
project: portfolio

services:
  - name: portfolio
    image: markmorcos/portfolio
    port: 80

    ingress:
      host: morcos.tech
      path: /
      pathType: Prefix
