services:
  portfolio:
    build:
      context: ./portfolio
      dockerfile: Dockerfile.development
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./portfolio
          target: /app
          ignore:
            - node_modules
