name: portfolio

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger infrastructure deployment
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INFRASTRUCTURE_TOKEN }}
          repository: markmorcos/infrastructure
          event-type: deploy-portfolio
          client-payload: '{"project_name": "portfolio", "deployment_token": "${{ secrets.DEPLOYMENT_TOKEN }}","deployment_version": "${{ github.sha }}"}'
